# Generated by Django 5.0.7 on 2024-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_lunchmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('annual_leaves', models.IntegerField()),
                ('casual_leaves', models.IntegerField()),
                ('medical_leaves', models.IntegerField()),
            ],
            options={
                'db_table': 'AllocatedLeaves',
            },
        ),
    ]
