# Generated by Django 5.0.7 on 2024-07-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_allocatedleaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('leave_type', models.CharField(max_length=50)),
                ('leave_taken_count', models.IntegerField(default=0)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.employees')),
            ],
            options={
                'db_table': 'LeavesTaken',
            },
        ),
        migrations.DeleteModel(
            name='Leaves',
        ),
    ]
