# Generated by Django 5.0.7 on 2024-07-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_remove_employees_leaves_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday_lunch_iterator', models.IntegerField()),
                ('weekday_lunch_iterator', models.IntegerField()),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
