# Generated by Django 5.0.7 on 2024-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='lunch_time',
            field=models.TimeField(default='15:00:00'),
        ),
    ]
