# Generated by Django 5.0.7 on 2024-07-26 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_admin_lunch_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('likes', models.JSONField(blank=True, default=list)),
                ('dislikes', models.JSONField(blank=True, default=list)),
                ('lunch_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.lunchmenu')),
            ],
            options={
                'db_table': 'lunch_review',
            },
        ),
    ]
