# Generated by Django 5.0.7 on 2024-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_employees_groups_employees_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('S-HR', 'Senior HR'), ('J-HR', 'Junior HR'), ('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('Employee', 'Employee')], default='Employee', max_length=255),
        ),
    ]
