# Generated by Django 5.0.7 on 2024-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestaken',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
