# Generated by Django 5.0.7 on 2024-08-07 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday_lunch_iterator', models.IntegerField()),
                ('weekday_lunch_iterator', models.IntegerField()),
                ('lunch_time', models.TimeField(default='15:00:00')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'LunchMenu',
            },
        ),
        migrations.CreateModel(
            name='LunchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('likes', models.JSONField(blank=True, default=list)),
                ('dislikes', models.JSONField(blank=True, default=list)),
                ('lunch_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.lunchmenu')),
            ],
            options={
                'db_table': 'LunchReview',
            },
        ),
    ]
